COURT_LENGTH = 78
COURT_WIDTH_DOUBLES = 36
COURT_WIDTH_SINGLES = 27
SERVICE_LINE_DIST = 21
WORLD_PTS = {"bottom_left": (-COURT_WIDTH_DOUBLES/2, -COURT_LENGTH/2),
				"bottom_right": (COURT_WIDTH_DOUBLES/2, -COURT_LENGTH/2),
				"top_right": (COURT_WIDTH_DOUBLES/2, COURT_LENGTH/2),
				"top_left": (-COURT_WIDTH_DOUBLES/2, COURT_LENGTH/2)}

DOUBLES_CORNERS = {"bottom_left": (-COURT_WIDTH_DOUBLES/2, -COURT_LENGTH/2),
				"bottom_right": (COURT_WIDTH_DOUBLES/2, -COURT_LENGTH/2),
				"top_right": (COURT_WIDTH_DOUBLES/2, COURT_LENGTH/2),
				"top_left": (-COURT_WIDTH_DOUBLES/2, COURT_LENGTH/2)}

SINGLES_CORNERS = {"bottom_left": (-COURT_WIDTH_SINGLES/2, -COURT_LENGTH/2),
				"bottom_right": (COURT_WIDTH_SINGLES/2, -COURT_LENGTH/2),
				"top_right": (COURT_WIDTH_SINGLES/2, COURT_LENGTH/2),
				"top_left": (-COURT_WIDTH_SINGLES/2, COURT_LENGTH/2)}

SERVICE_CORNERS = {"bottom_left": (-COURT_WIDTH_SINGLES/2, -SERVICE_LINE_DIST),
				"bottom_right": (COURT_WIDTH_SINGLES/2, -SERVICE_LINE_DIST),
				"top_right": (COURT_WIDTH_SINGLES/2, SERVICE_LINE_DIST),
				"top_left": (-COURT_WIDTH_SINGLES/2, SERVICE_LINE_DIST)}